package GUI_agora;

import FNC_agora.Product;
import FNC_agora.Vendor;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 * GUI_BrowseItems is a view allowing customer to browse items and add them to cart
 *
 * @author Maciej Medyk and Caio Farias
 */
public class GUI_BrowseItems extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_VendorInventory
     */
    public GUI_BrowseItems() {
        initComponents();
        mWelcome.setText("Welcome: " + Agora.um.loggedName);
        ArrayList<Vendor> vl = Agora.um.getVendors();
        mpanel = new JPanel();
        npanel = new JPanel();
        mpanel.setLayout(new BoxLayout(mpanel, BoxLayout.Y_AXIS));
        npanel.setLayout(new BorderLayout());
        mpanel.setAlignmentX(LEFT_ALIGNMENT);
        mpanel.setAlignmentY(TOP_ALIGNMENT);
        for(Vendor v : vl)
        {
            for(Product p : v.viewInventory())
            {
                if (p.getQuantity() > 0)
                {
                    item = new GUI_CustomerLineItem(p, this);
                    mpanel.add(item);
                    mpanel.setAlignmentX(LEFT_ALIGNMENT);
                    mpanel.setAlignmentY(TOP_ALIGNMENT);
                }
            }
        }
        npanel.add(mpanel, BorderLayout.NORTH);
        mainPanel.getViewport().add(npanel);
        DecimalFormat df = new DecimalFormat("####0.00");
        cartItems.setText('$' + df.format(Agora.um.cLoggedUser.getCart().getCartAmount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        mWelcome = new javax.swing.JLabel();
        viewCart = new javax.swing.JButton();
        cartItems = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setTitle("Browse Items");
        setToolTipText("");

        mainPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        mainPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        mainPanel.setAlignmentX(0.0F);
        mainPanel.setAlignmentY(0.0F);
        mainPanel.setOpaque(true);

        jButton1.setText("Logout");
        jButton1.setToolTipText("Logout Button");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mWelcome.setText("Welcome: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mWelcome)
                                .addContainerGap(488, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(mWelcome))
                                .addContainerGap(8, Short.MAX_VALUE))
        );

        viewCart.setText("View Cart");
        viewCart.setToolTipText("View Cart Button");
        viewCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartActionPerformed(evt);
            }
        });

        cartItems.setEditable(false);
        cartItems.setBackground(new java.awt.Color(232, 232, 232));
        cartItems.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        cartItems.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        cartItems.setText("$0.00");
        cartItems.setFocusable(false);

        jLabel1.setText("      View         Product Name                           Product Description                                                                                                                                                    Price            Qty ");

        jLabel2.setText("Cart Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(118, 118, 118)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cartItems, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(viewCart))
                                        .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(viewCart)
                                                        .addComponent(cartItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    /**
     * Logs out customer out of session
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        Agora.desktop.removeAll();
        GUI_Login login = new GUI_Login("");
        Agora.desktop.add(login);
        login.setVisible(true);
    }

    /**
     * Opens cart window
     *
     * @param evt
     */
    private void viewCartActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        GUI_Cart ct = new GUI_Cart(this);
        ct.setLocation((Agora.desktop.getWidth() - ct.getWidth())/2,(Agora.desktop.getHeight() - ct.getHeight())/2);
        Agora.desktop.add(ct, new Integer(10));
        ct.setVisible(true);

    }


    /**
     * Refreshes the main panel containing products
     */
    public void repaintMainPanel()
    {
        ArrayList<Vendor> vl = Agora.um.getVendors();
        mpanel.removeAll();
        npanel.removeAll();
        for(Vendor v : vl)
        {
            for(Product p : v.viewInventory())
            {
                if (p.getQuantity() > 0)
                {
                    item = new GUI_CustomerLineItem(p, this);
                    mpanel.add(item);
                    mpanel.setAlignmentX(LEFT_ALIGNMENT);
                    mpanel.setAlignmentY(TOP_ALIGNMENT);
                }
            }
        }
        npanel.add(mpanel, BorderLayout.NORTH);
        mainPanel.getViewport().add(npanel);
        mainPanel.getViewport().revalidate();
        mainPanel.getViewport().repaint();
    }

    /**
     * Updates a cart amount
     *
     * @param s amount string
     */
    public void updateCartAmount(String s)
    {
        cartItems.setText('$' + s);
    }


    // Variables declaration - do not modify                     
    private javax.swing.JTextField cartItems;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mWelcome;
    private javax.swing.JScrollPane mainPanel;
    private javax.swing.JButton viewCart;
    // End of variables declaration                   
    private javax.swing.JPanel mpanel;
    private javax.swing.JPanel npanel;
    private GUI_CustomerLineItem item;

}
