package GUI_agora;

import FNC_agora.Product;
import java.text.DecimalFormat;

/**
 * GUI_VendorLineItem is inner panel of VendorInventory frame
 *
 * @author Maciej Medyk and Caio Farias
 */
public class GUI_VendorLineItem extends javax.swing.JPanel {

    /**
     * Creates new form GUI_LineItem
     * @param p
     */
    public GUI_VendorLineItem(Product p, GUI_VendorInventory vi) {
        initComponents();
        mVi = vi;
        mP = p;
        mName.setText(p.getProductName());
        mDesc.setText(p.getProductDec());
        DecimalFormat df = new DecimalFormat("####0.00");
        mPrice.setText('$' + df.format(p.getSellPrice()));
        mCost.setText('$' + df.format(p.getCostPrice()));
        mQuantity.setText(Integer.toString(p.getQuantity()));
    }

    public GUI_VendorLineItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        mName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mDesc = new javax.swing.JLabel();
        mPrice = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        mQuantity = new javax.swing.JLabel();
        mCost = new javax.swing.JLabel();

        setBackground(new java.awt.Color(224, 227, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mName.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        mName.setForeground(new java.awt.Color(51, 51, 255));
        mName.setText("ProductName");
        add(mName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        jButton1.setText("Edit");
        jButton1.setToolTipText("Edit Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 3, -1, -1));

        mDesc.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        mDesc.setText("Product Desc");
        add(mDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        mPrice.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        mPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mPrice.setText("Price");
        add(mPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 3));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 970, 3));

        mQuantity.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        mQuantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mQuantity.setText("Quantity");
        add(mQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        mCost.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        mCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mCost.setText("Cost");
        add(mCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));
    }// </editor-fold>

    /**
     * Opens edit product view
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        GUI_EditProduct ep = new GUI_EditProduct(mP, mVi);
        ep.setLocation((Agora.desktop.getWidth() - ep.getWidth())/2,(Agora.desktop.getHeight() - ep.getHeight())/2);
        Agora.desktop.add(ep);
        ep.setVisible(true);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel mCost;
    private javax.swing.JLabel mDesc;
    private javax.swing.JLabel mName;
    private javax.swing.JLabel mPrice;
    private javax.swing.JLabel mQuantity;
    // End of variables declaration
    private Product mP;
    private GUI_VendorInventory mVi;
}