package GUI_agora;

import FNC_agora.Vendor;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;

/**
 * GUI_AddProduct is view responsible for adding new products to vendor inventory
 *
 * @author Maciej Medyk and Caio Farias
 */
public class GUI_AddProduct extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_AddProduct
     */
    public GUI_AddProduct(GUI_VendorInventory vi) {

        initComponents();
        mLabel.setVisible(false);
        mVi = vi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mProductName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mProductDesc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mSellPrice = new javax.swing.JTextField();
        mInvoicePrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mQuantity = new javax.swing.JTextField();
        mCategory = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mLabel = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Edit Product");
        setAlignmentX(300.0F);
        setAlignmentY(300.0F);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jLabel1.setText("Product Name");

        jLabel2.setText("Product Description");

        mProductDesc.setColumns(20);
        mProductDesc.setLineWrap(true);
        mProductDesc.setRows(5);
        jScrollPane1.setViewportView(mProductDesc);

        jLabel3.setText("Sell Price");

        jLabel4.setText("Invoice Price");

        jLabel5.setText("Category");


        mCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Games", "Movies", "Books" }));

        jLabel6.setText("Quantity");

        jButton1.setText("Add Product");
        jButton1.setToolTipText("Update Product Button");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mLabel.setForeground(new java.awt.Color(255, 0, 0));
        mLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(mSellPrice)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(mInvoicePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(mQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(mProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(mCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(mLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(mSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mInvoicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * Adds new item and provides verification
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Vendor v = Agora.um.vLoggedUser;
        Double p;
        Double c;
        Integer q;
        try
        {
            if (mProductName.getText().equals("") || mProductDesc.getText().equals("") || mCategory.getSelectedItem().toString().equals("") || mInvoicePrice.getText().equals("") || mSellPrice.getText().equals("") || mQuantity.getText().equals(""))
            {
                throw new Exception("All fields required");
            }
            p = Double.parseDouble(mInvoicePrice.getText());
            c = Double.parseDouble(mSellPrice.getText());
            q = Integer.parseInt(mQuantity.getText());

            v.addToInventory(mProductName.getText(), mProductDesc.getText(), mCategory.getSelectedItem().toString(), Double.parseDouble(mSellPrice.getText()), Double.parseDouble(mInvoicePrice.getText()), Integer.parseInt(mQuantity.getText()));
            mVi.repaintMainPanel();
            this.setVisible(false);
        }
        catch(Exception e)
        {
            if (e.toString().equals("java.lang.Exception: All fields required"))
            {
                mLabel.setText("All fields required");
            }
            else
            {
                mLabel.setText("Prices and Quanities must be Numerical Values");
            }
            mLabel.setVisible(true);
        }

        try
        {
            this.serialization();
        }
        catch (Exception e)
        {

        }
    }

    /**
     * Saves the status of the program
     *
     * @throws IOException
     * @throws ClassNotFoundException
     */
    private void serialization() throws IOException, ClassNotFoundException
    {
        ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream("agora.dat"));
        output.writeObject(Agora.um);
        output.close();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox mCategory;
    private javax.swing.JTextField mInvoicePrice;
    private javax.swing.JLabel mLabel;
    private javax.swing.JTextArea mProductDesc;
    private javax.swing.JTextField mProductName;
    private javax.swing.JTextField mQuantity;
    private javax.swing.JTextField mSellPrice;
    // End of variables declaration                   
    private GUI_VendorInventory mVi;
}
