package GUI_agora;

import FNC_agora.Cart;
import FNC_agora.Customer;
import FNC_agora.Order;
import FNC_agora.Product;
import FNC_agora.Vendor;
import java.awt.BorderLayout;
import static java.awt.Component.LEFT_ALIGNMENT;
import static java.awt.Component.TOP_ALIGNMENT;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 * GUI_OrderHistory shows vendor all items ordered and by whom
 *
 * @author Maciej Medyk and Caio Farias
 */
public class GUI_OrderHistory extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_AddProduct
     */
    public GUI_OrderHistory() {

        initComponents();
        Vendor v = Agora.um.vLoggedUser;
        mpanel = new JPanel();
        npanel = new JPanel();
        mpanel.setLayout(new BoxLayout(mpanel, BoxLayout.Y_AXIS));
        npanel.setLayout(new BorderLayout());
        ArrayList<Product> mp = v.viewInventory();

        ArrayList<Customer> cs = Agora.um.getCustomers();
        for (Customer c : cs)
        {
            ArrayList<Order> os = c.getOrders();
            for (Order o : os)
            {
                Cart ct = o.getCart();
                ArrayList<Product> ps = ct.getCartItems();
                for (Product pi : ps)
                {
                    for (Product pj : mp)
                    {
                        if(pi.getProductID() == pj.getProductID())
                        {
                            if(pi.getQuantity() > 0)
                            {
                                item = new GUI_OrderLineItem(pi, c);
                                mpanel.add(item);
                                mpanel.setAlignmentX(LEFT_ALIGNMENT);
                                mpanel.setAlignmentY(TOP_ALIGNMENT);
                                npanel.add(mpanel, BorderLayout.NORTH);
                            }
                        }
                    }
                }
            }
        }
        mainPanel.getViewport().add(npanel);
        mainPanel.getViewport().revalidate();
        mainPanel.getViewport().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Order History");
        setAlignmentX(300.0F);
        setAlignmentY(300.0F);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        mLabel.setForeground(new java.awt.Color(255, 0, 0));
        mLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mainPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        mainPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel1.setText("  Product Name                                                               Category                                     Quantity                   Total          Customer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(mLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 249, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(mainPanel)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        



    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mLabel;
    private javax.swing.JScrollPane mainPanel;
    // End of variables declaration                   
    private javax.swing.JPanel mpanel;
    private javax.swing.JPanel npanel;
    private GUI_OrderLineItem item;
}
