package GUI_agora;

import FNC_agora.Customer;
import FNC_agora.Vendor;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;

/**
 * GUI_ForgotPassword view allows user to change his password
 *
 * @author Maciej Medyk and Caio Farias
 */
public class GUI_ForgotPassword extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_Login
     */
    public GUI_ForgotPassword() {
        initComponents();
        mMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mDate = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        mPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        mMessage = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setText("Back");
        jButton1.setToolTipText("Back To Login Button");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Password");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Username");

        jLabel3.setText("Full Name");

        jLabel4.setText("Email");

        jLabel5.setText("Date Of Birth");

        jLabel6.setText("New Password");

        jButton2.setText("Update Password");
        jButton2.setToolTipText("Update Password Button");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        mMessage.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        mMessage.setForeground(new java.awt.Color(255, 102, 102));
        mMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mMessage.setText("Password Updated");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mEmail)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                                        .addComponent(mName)
                                        .addComponent(mUsername)
                                        .addComponent(mDate, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mMessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(354, 354, 354)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * Cancels action and goes back to login
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
        GUI_Login login = new GUI_Login("");
        Agora.desktop.add(login);
        login.setVisible(true);
    }

    /**
     * Verifies the user data and updates password
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int i = 0;
        for (int k = 0; k < Agora.um.getVendors().size(); k++)
        {
            Vendor user = Agora.um.getVendor(k);
            if (user.getUsername().equals(mUsername.getText()) && user.getEmail().equals(mEmail.getText()) && user.getFullName().equals(mName.getText()) && user.getDateOfBirth().equals(mDate.getText()))
            {
                user.setPassword(mPassword.getText());
                mMessage.setText("Password Change Successfull");
                mMessage.setVisible(true);
                i++;
                try
                {
                    this.serialization();
                }
                catch (Exception e)
                {

                }
                return;
            }
        }
        for (int k = 0; k < Agora.um.getCustomers().size(); k++)
        {
            Customer user = Agora.um.getCustomer(k);
            if (user.getUsername().equals(mUsername.getText()) && user.getEmail().equals(mEmail.getText()) && user.getFullName().equals(mName.getText()) && user.getDateOfBirth().equals(mDate.getText()))
            {
                user.setPassword(mPassword.getText());
                mMessage.setText("Password Change Successfull");
                mMessage.setVisible(true);
                i++;
                try
                {
                    this.serialization();
                }
                catch (Exception e)
                {

                }
                return;
            }
        }
        if (i == 0)
        {
            mMessage.setText("Password Change Unsuccessfull");
            i = 0;
        }
        mMessage.setVisible(true);


    }

    /**
     * Saves the status of the program
     *
     * @throws IOException
     * @throws ClassNotFoundException
     */
    private void serialization() throws IOException, ClassNotFoundException
    {
        ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream("agora.dat"));
        output.writeObject(Agora.um);
        output.close();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField mDate;
    private javax.swing.JTextField mEmail;
    private javax.swing.JLabel mMessage;
    private javax.swing.JTextField mName;
    private javax.swing.JPasswordField mPassword;
    private javax.swing.JTextField mUsername;
    // End of variables declaration                   
}
