package GUI_agora;

import FNC_agora.Cart;
import FNC_agora.Customer;
import FNC_agora.Product;
import FNC_agora.Vendor;
import static java.awt.Component.LEFT_ALIGNMENT;
import static java.awt.Component.TOP_ALIGNMENT;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 * GUI_CartLineItem is a inner panel in Cart View
 *
 * @author Maciej Medyk and Caio Farias
 */
public class GUI_CartLineItem extends javax.swing.JPanel {

    /**
     * Creates new form GUI_LineItem
     * @param p
     */
    public GUI_CartLineItem(Product p, GUI_Cart ct, GUI_BrowseItems bi) {
        initComponents();
        mCt = ct;
        mP = p;
        mBi = bi;
        mName.setText(p.getProductName());
        DecimalFormat df = new DecimalFormat("####0.00");
        mPrice.setText('$' + df.format(p.getSellPrice()));
        mQty.setText(Integer.toString(p.getQuantity()));
        double totalPrice = p.getSellPrice()*p.getQuantity();
        mTotalPrice.setText('$' + df.format(totalPrice));
        int q = p.getQuantity();
        //if (q > 8) q = 8;
        for (int i = q; i >= 0; i--)
        {
            mQuantity.addItem(i);
        }
    }

    public GUI_CartLineItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        mName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mPrice = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        mQuantity = new javax.swing.JComboBox();
        mQty = new javax.swing.JLabel();
        mTotalPrice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(224, 227, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mName.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        mName.setForeground(new java.awt.Color(51, 51, 255));
        mName.setText("ProductName");

        add(mName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        jButton1.setText("Update");
        jButton1.setToolTipText("Update Quanity Button");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 3, -1, -1));

        mPrice.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        mPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mPrice.setText("Price");
        add(mPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 3));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 700, 3));

        mQuantity.setMaximumRowCount(10);
        add(mQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 4, 50, -1));

        mQty.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        mQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mQty.setText("Quantity");
        add(mQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        mTotalPrice.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        mTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mTotalPrice.setText("Total Price");
        add(mTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));
    }// </editor-fold>

    /**
     * Adds product to the cart
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Customer c = Agora.um.cLoggedUser;
//        ArrayList<Product> vI = c.getCart().getVendorItems();
        Product found = mP;
        ArrayList<Vendor> vl = Agora.um.getVendors();
        for(Vendor v : vl)
        {
            for(Product p : v.viewInventory())
            {
                if(p.getProductID()== mP.getProductID())
                {
                    found = p;
                    //System.out.println("Product found.");
                }
            }
        }
        int qty = Integer.parseInt( (String) mQuantity.getSelectedItem());
        found.setQuantity(found.getQuantity() + mP.getQuantity() - qty);
        mP.setQuantity(qty);
        Cart ct = c.getCart();
        double amount = ct.getCartAmount();
        DecimalFormat df = new DecimalFormat("####0.00");
        mCt.setCartTotal();
        mCt.repaintMainPanel();
        mBi.repaintMainPanel();
        mBi.updateCartAmount(df.format(amount));

    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel mName;
    private javax.swing.JLabel mPrice;
    private javax.swing.JLabel mQty;
    private javax.swing.JComboBox mQuantity;
    private javax.swing.JLabel mTotalPrice;
    // End of variables declaration
    private Product mP;
    private GUI_Cart mCt;
    private GUI_BrowseItems mBi;
}
