package GUI_agora;

import FNC_agora.Cart;
import FNC_agora.Customer;
import FNC_agora.Order;
import FNC_agora.Product;
import FNC_agora.Vendor;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.math.BigInteger;
import java.text.DecimalFormat;

/**
 * GUI_Checkout is a view that allows customer checkout and create order 
 *
 * @author Maciej Medyk and Caio Farias
 */
public class GUI_Checkout extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_AddProduct
     */
    public GUI_Checkout(Cart c, GUI_Cart ct, GUI_BrowseItems bi) {
        initComponents();
        mBi = bi;
        mCart = c;
        mGUICart = ct;
        Customer cust = Agora.um.cLoggedUser;
        mCustomerName.setText(cust.getFullName());
        DecimalFormat df = new DecimalFormat("####0.00");
        mCartTotal.setText('$' + df.format(cust.getCart().getCartAmount()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mCustomerName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mCreditCardNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mMonth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mYear = new javax.swing.JTextField();
        mZip = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mCartTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Checkout");
        setAlignmentX(300.0F);
        setAlignmentY(300.0F);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        mCustomerName.setEditable(false);
        mCustomerName.setBackground(new java.awt.Color(232, 232, 232));
        mCustomerName.setText("Name");
        mCustomerName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mCustomerName.setEnabled(false);

        jLabel1.setText(" Customer");

        mLabel.setForeground(new java.awt.Color(255, 0, 0));
        mLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mLabel.setText(" ");

        jLabel4.setText(" Credit Card Number");

        jLabel2.setText(" Expiration Date");

        mMonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("/");

        mYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mZip.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setText(" Zipcode");

        jLabel6.setText(" Order Amount");

        mCartTotal.setEditable(false);
        mCartTotal.setBackground(new java.awt.Color(232, 232, 232));
        mCartTotal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        mCartTotal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        mCartTotal.setText("$0.00");
        mCartTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mCartTotal.setEnabled(false);

        jButton1.setForeground(new java.awt.Color(0, 204, 102));
        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 51, 0));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mCustomerName)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4)
                                        .addComponent(mCreditCardNo)
                                        .addComponent(mLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(mMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(mYear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel2)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel6)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(mZip, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(mCartTotal)
                                                                                .addContainerGap())))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(mCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mCreditCardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(mYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mCartTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mLabel)
                                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>                        


    /**
     * Cancels checkout and returns back to the cart
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        GUI_Cart c = mGUICart;
        c.setLocation((Agora.desktop.getWidth() - c.getWidth())/2,(Agora.desktop.getHeight() - c.getHeight())/2);
        c.setVisible(true);
        this.setVisible(false);
    }

    /**
     * Validates payment information and completes the order
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String ccn = mCreditCardNo.getText();
        if (ccn.length() == 16)
        {
            int cc1 = 0;
            int cc2 = 0;
            try
            {
                cc1 = Integer.parseInt(ccn.substring(0, 7));
                cc2 = Integer.parseInt(ccn.substring(8, 15));
            }
            catch(Exception e)
            {
                mLabel.setText("Credit card number cannot contain letters");
            }
            if (cc1 > 3999999 && cc1 < 6000000)
            {
                try
                {
                    int month = Integer.parseInt(mMonth.getText());
                    int year = Integer.parseInt(mYear.getText());
                    if (month < 1 || month > 12 || mMonth.getText().length() > 2)
                    {
                        throw new Exception("Invalid Expiration Date");
                    }
                    else
                    {
                        if(year < 1970 || year > 2200 || mYear.getText().length() != 4)
                        {
                            throw new Exception("Invalid Expiration Date");
                        }
                        try
                        {
                            int zip = Integer.parseInt(mZip.getText());
                            if (zip < 10000 || zip > 99999 || mZip.getText().length() != 5)
                            {
                                throw new Exception("Invalid Zip");
                            }
                            Cart c = mCart.clone();
                            Order o = new Order(c, Agora.um.cLoggedUser);
                            Agora.um.cLoggedUser.addOrder(o);
                            mCart.clear();
                            mBi.updateCartAmount("0.00");
                            mGUICart.repaintMainPanel();
                            GUI_Note n = new GUI_Note("Order Has Been Processed");
                            this.setVisible(false);
                            n.setLocation((Agora.desktop.getWidth() - n.getWidth())/2,(Agora.desktop.getHeight() - n.getHeight())/2);
                            Agora.desktop.add(n, new Integer(10));
                            n.setVisible(true);
                            try
                            {
                                serialization();
                            }
                            catch(Exception e1)
                            {

                            }
                        }
                        catch(Exception e2)
                        {
                            mLabel.setText("Invalid Zip Code");
                        }
                    }
                }
                catch(Exception e)
                {
                    mLabel.setText("Invalid Month and Year");
                }
            }
            else
            {
                mLabel.setText("Credit Card must be Visa or Mastercard");
            }
        }
        else
        {
            mLabel.setText("Credit card number must have 16 digits");
        }




    }

    /**
     * Saves the state of the program
     *
     * @throws IOException
     * @throws ClassNotFoundException
     */
    private void serialization() throws IOException, ClassNotFoundException
    {
        ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream("agora.dat"));
        output.writeObject(Agora.um);
        output.close();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mCartTotal;
    private javax.swing.JTextField mCreditCardNo;
    private javax.swing.JTextField mCustomerName;
    private javax.swing.JLabel mLabel;
    private javax.swing.JTextField mMonth;
    private javax.swing.JTextField mYear;
    private javax.swing.JTextField mZip;
    // End of variables declaration                   
    private Cart mCart;
    private GUI_Cart mGUICart;
    private GUI_BrowseItems mBi;
}
