package GUI_agora;

import FNC_agora.Cart;
import FNC_agora.Customer;
import FNC_agora.Order;
import FNC_agora.Product;
import FNC_agora.Vendor;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.math.BigInteger;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 * GUI_AccountSummary displays the revenues, costs, profits of vendor
 *
 * @author Maciej Medyk and Caio Farias
 */
public class GUI_AccountSummary extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_AddProduct
     */
    public GUI_AccountSummary() {
        initComponents();

        double revenues = 0;
        double costs = 0;
        double profits = 0;
        Vendor v = Agora.um.vLoggedUser;
        ArrayList<Product> mp = v.viewInventory();
        ArrayList<Customer> cs = Agora.um.getCustomers();
        for (Customer c : cs)
        {
            ArrayList<Order> os = c.getOrders();
            for (Order o : os)
            {
                Cart ct = o.getCart();
                ArrayList<Product> ps = ct.getCartItems();
                for (Product pi : ps)
                {
                    for (Product pj : mp)
                    {
                        if(pi.getProductID() == pj.getProductID())
                        {
                            double revenue = pi.getQuantity() * pi.getSellPrice();
                            revenues += revenue;
                            double cost = pi.getQuantity() * pi.getCostPrice();
                            costs += cost;
                        }
                    }
                }
            }
        }
        profits = revenues - costs;
        DecimalFormat df = new DecimalFormat("####0.00");
        mRevenues.setText(df.format(revenues));
        mCosts.setText(df.format(costs));
        mProfits.setText(df.format(profits));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mRevenues = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mCosts = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mProfits = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Account Summary");
        setAlignmentX(300.0F);
        setAlignmentY(300.0F);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        mRevenues.setEditable(false);
        mRevenues.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        mRevenues.setText("$0.00");
        mRevenues.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mRevenues.setEnabled(false);

        jLabel1.setText("Revenues");

        jLabel4.setText("Costs");

        mCosts.setEditable(false);
        mCosts.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        mCosts.setText("$0.00");
        mCosts.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mCosts.setEnabled(false);

        jLabel2.setText("Profits");

        mProfits.setEditable(false);
        mProfits.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        mProfits.setText("$0.00");
        mProfits.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mProfits.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(mCosts, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(mProfits, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mRevenues, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(mRevenues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mCosts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mProfits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>                        



    // Variables declaration - do not modify
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mCosts;
    private javax.swing.JTextField mProfits;
    private javax.swing.JTextField mRevenues;
    // End of variables declaration                   
}
