package GUI_agora;

import FNC_agora.Cart;
import FNC_agora.Customer;
import FNC_agora.Product;
import java.text.DecimalFormat;
import java.util.ArrayList;

/**
 * GUI_CustomerLineItem is inner panel in Browse Items view
 *
 * @author Maciej Medyk and Caio Farias
 */
public class GUI_CustomerLineItem extends javax.swing.JPanel {

    /**
     * Creates new form GUI_LineItem
     * @param p
     */
    public GUI_CustomerLineItem(Product p, GUI_BrowseItems vi) {
        initComponents();
        mBi = vi;
        mP = p;
        mName.setText(p.getProductName());
        mDesc.setText(p.getProductDec());
        DecimalFormat df = new DecimalFormat("####0.00");
        mPrice.setText('$' + df.format(p.getSellPrice()));
        int q = p.getQuantity();
        //if (q > 8) q = 8;
        for (int i = 1; i <= q; i++)
        {
            mQuantity.addItem(i);
        }
    }

    public GUI_CustomerLineItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        mName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mDesc = new javax.swing.JLabel();
        mPrice = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        mQuantity = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(224, 227, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mName.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        mName.setForeground(new java.awt.Color(51, 51, 255));
        mName.setText("ProductName");

        add(mName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jButton1.setText("Add");
        jButton1.setToolTipText("Add To Cart Button");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 3, -1, -1));

        mDesc.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        mDesc.setText("Product Desc");
        add(mDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        mPrice.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        mPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mPrice.setText("Price");
        add(mPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 3));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 970, 3));

        mQuantity.setMaximumRowCount(10);
        add(mQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 4, 50, -1));

        jButton2.setText("View");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, -1, -1));
    }// </editor-fold>

    /**
     * Adds item to the cart
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Customer c = Agora.um.cLoggedUser;
        Product nP = mP.getClone();
        int qty = Integer.parseInt( (String) mQuantity.getSelectedItem());
        mP.setQuantity(mP.getQuantity()-qty);
        nP.setQuantity(qty);
        ArrayList<Product> pl = c.getCart().getCartItems();
        int count = 0;
        for (Product p : pl)
        {
            if(p.getProductID() == mP.getProductID())
            {
                nP = p;
                nP.setQuantity(p.getQuantity()+ qty);
                count = 1;
            }
        }
        if (count == 0)
        {
            c.addItemToCart(nP);
        }
        Cart ct = c.getCart();
        double amount = ct.getCartAmount();
        DecimalFormat df = new DecimalFormat("####0.00");
        mBi.updateCartAmount(df.format(amount));
        mBi.repaintMainPanel();
    }

    /**
     * Opens view product screen
     *
     * @param evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        GUI_ViewProduct vp = new GUI_ViewProduct(mP, mBi);
        vp.setLocation((Agora.desktop.getWidth() - vp.getWidth())/2,(Agora.desktop.getHeight() - vp.getHeight())/2);
        Agora.desktop.add(vp, new Integer(10));
        vp.setVisible(true);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel mDesc;
    private javax.swing.JLabel mName;
    private javax.swing.JLabel mPrice;
    private javax.swing.JComboBox mQuantity;
    // End of variables declaration
    private Product mP;
    private GUI_BrowseItems mBi;
}
